# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKUnX-ED41q1zEjasxWmThW1PxqjLa6-
"""



import openai
import streamlit as st

# OpenAI API key ko set karein
openai.api_key = 'sk-5AF0armObv3N6VvreKReGSzeenA7y_39d0lCF0QcrjT3BlbkFJl-CTfDyW2aIRLw0vstlkf5_zckEL6yBU0SZelkubIA'

def generate_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0.7
    )
    return response.choices[0].text.strip()

# Streamlit app ka front-end
st.title("AI Chatbot using OpenAI")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")

with open('app.py', 'w') as f:
    f.write("""
import openai
import streamlit as st

openai.api_key = 'aapki_openai_api_key'

def generate_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0.7
    )
    return response.choices[0].text.strip()

st.title("AI Chatbot using OpenAI")

user_input = st.text_input("You: ", "Hello, how are you?")

if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")
""")