# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKUnX-ED41q1zEjasxWmThW1PxqjLa6-
"""



import openai
import streamlit as st

# OpenAI API key ko set karein
openai.api_key = 'sk-5AF0armObv3N6VvreKReGSzeenA7y_39d0lCF0QcrjT3BlbkFJl-CTfDyW2aIRLw0vstlkf5_zckEL6yBU0SZelkubIA'

def generate_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0.7
    )
    return response.choices[0].text.strip()

# Streamlit app ka front-end
st.title("AI Chatbot using OpenAI")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")

import openai
import streamlit as st

# OpenAI API key ko set karein (yahaan apni new API key daalein)
openai.api_key = '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'

def generate_response(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-4",  # GPT-4 model use kar rahe hain
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response['choices'][0]['message']['content'].strip()

# Streamlit app ka front-end
st.title("AI Chatbot using GPT-4")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

# Jab user input kare aur 'Send' button dabaye to AI response generate karega
if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")

# prompt: PLZ FIX ERROR OF LAST PROMPT

import openai
import streamlit as st



# OpenAI API key ko set karein
openai.api_key = 'sk-5AF0armObv3N6VvreKReGSzeenA7y_39d0lCF0QcrjT3BlbkFJl-CTfDyW2aIRLw0vstlkf5_zckEL6yBU0SZelkubIA'

def generate_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0.7
    )
    return response.choices[0].text.strip()

# Streamlit app ka front-end
st.title("AI Chatbot using OpenAI")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")


# OpenAI API key ko set karein (yahaan apni new API key daalein)
openai.api_key = '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'

def generate_response(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # GPT-3.5-turbo model use kar rahe hain
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response['choices'][0]['message']['content'].strip()

# Streamlit app ka front-end
st.title("AI Chatbot using GPT-4")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

# Jab user input kare aur 'Send' button dabaye to AI response generate karega
if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")

# prompt: plz fix error in line 2 of last prompt

import openai
import streamlit as st



# OpenAI API key ko set karein
openai.api_key = 'sk-5AF0armObv3N6VvreKReGSzeenA7y_39d0lCF0QcrjT3BlbkFJl-CTfDyW2aIRLw0vstlkf5_zckEL6yBU0SZelkubIA'

def generate_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0.7
    )
    return response.choices[0].text.strip()

# Streamlit app ka front-end
st.title("AI Chatbot using OpenAI")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")


# OpenAI API key ko set karein (yahaan apni new API key daalein)
openai.api_key = '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'

def generate_response(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # GPT-3.5-turbo model use kar rahe hain
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response['choices'][0]['message']['content'].strip()

# Streamlit app ka front-end
st.title("AI Chatbot using GPT-4")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

# Jab user input kare aur 'Send' button dabaye to AI response generate karega
if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")



import openai
import streamlit as st

# OpenAI API key ko set karein
openai.api_key = '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'

def generate_response(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-4",  # GPT-4 model use kar rahe hain
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response['choices'][0]['message']['content'].strip()

# Streamlit app ka front-end
st.title("AI Chatbot using GPT-4")

# User input ke liye text box
user_input = st.text_input("You: ", "Hello, how are you?")

# Jab user input kare aur 'Send' button dabaye to AI response generate karega
if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")

with open('app.py', 'w') as f:
    f.write("""
import openai
import streamlit as st

openai.api_key = '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'

def generate_response(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response['choices'][0]['message']['content'].strip()

st.title("AI Chatbot using GPT-4")

user_input = st.text_input("You: ", "Hello, how are you?")

if st.button('Send'):
    response = generate_response(user_input)
    st.write(f"AI: {response}")
""")
