# -*- coding: utf-8 -*-
"""Health and Fitness

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OPzDCeBqIfPzGxE3ZDYM0bmR8hifsid
"""



import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Web app ka title
st.title('Health and Fitness Dashboard')

# Section 1: Daily Step Count
st.header('Daily Steps Tracker')
steps = st.number_input('Enter your steps for today:')
if steps > 0:
    st.write(f"You have taken {steps} steps today!")

# Section 2: Daily Calorie Tracker
st.header('Calorie Intake Tracker')
calories = st.number_input('Enter your calorie intake for today:')
if calories > 0:
    st.write(f"You have consumed {calories} calories today!")

# Section 3: BMI Calculator
st.header('BMI Calculator')

# User input for height and weight
height = st.number_input('Enter your height (in meters):')
weight = st.number_input('Enter your weight (in kg):')

if height > 0 and weight > 0:
    # BMI calculation
    bmi = weight / (height ** 2)
    st.write(f"Your BMI is: {bmi:.2f}")

    # Categorize BMI
    if bmi < 18.5:
        st.write("You are underweight.")
    elif 18.5 <= bmi < 24.9:
        st.write("You have a normal weight.")
    elif 25 <= bmi < 29.9:
        st.write("You are overweight.")
    else:
        st.write("You are obese.")

# Section 4: Visualize Progress
st.header('Visualize Your Progress')

# Sample data for steps and calories
data = {
    'Days': ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'],
    'Steps': [3000, 5000, 7000, 8000, 10000],
    'Calories': [2000, 1800, 2100, 2300, 1900]
}

df = pd.DataFrame(data)

# Line chart for steps
st.subheader('Steps Progress Over 5 Days')
plt.figure(figsize=(10, 5))
plt.plot(df['Days'], df['Steps'], marker='o')
plt.title('Steps Over Time')
plt.xlabel('Days')
plt.ylabel('Steps')
plt.grid(True)
st.pyplot(plt)

# Bar chart for calorie intake
st.subheader('Calorie Intake Over 5 Days')
plt.figure(figsize=(10, 5))
plt.bar(df['Days'], df['Calories'], color='orange')
plt.title('Calories Over Time')
plt.xlabel('Days')
plt.ylabel('Calories')
st.pyplot(plt)



# Test karo steps aur calorie data ko Google Colab mein
import pandas as pd
import matplotlib.pyplot as plt

# Sample data
data = {
    'Days': ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'],
    'Steps': [3000, 5000, 7000, 8000, 10000],
    'Calories': [2000, 1800, 2100, 2300, 1900]
}

df = pd.DataFrame(data)

# Line chart for steps
plt.figure(figsize=(10, 5))
plt.plot(df['Days'], df['Steps'], marker='o')
plt.title('Steps Over Time')
plt.xlabel('Days')
plt.ylabel('Steps')
plt.grid(True)
plt.show()

# Bar chart for calorie intake
plt.figure(figsize=(10, 5))
plt.bar(df['Days'], df['Calories'], color='orange')
plt.title('Calories Over Time')
plt.xlabel('Days')
plt.ylabel('Calories')
plt.show()